#!/usr/bin/env python3
"""Generate the TableLore notebook rescue demo artifacts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
DEMO_ROOT = REPO_ROOT / "demo" / "notebook-rescue"
NOTEBOOK_PATH = DEMO_ROOT / "messy_revenue_exploration.ipynb"
DATA_PATH = DEMO_ROOT / "data" / "monthly_revenue.csv"
DEFAULT_OUTPUT_DIR = DEMO_ROOT / "output"


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def read_notebook_summary() -> tuple[int, int, bool]:
    notebook = json.loads(NOTEBOOK_PATH.read_text(encoding="utf-8"))
    cells = notebook.get("cells", [])
    code_cells = [cell for cell in cells if cell.get("cell_type") == "code"]
    source = "\n".join("".join(cell.get("source", [])) for cell in code_cells)
    has_hidden_state = "focus_segment" in source or "df = df[" in source
    return len(cells), len(code_cells), has_hidden_state


def clean_script(output_dir: Path) -> str:
    summary_path = output_dir / "cohort_revenue_summary.csv"
    return f'''#!/usr/bin/env python3
"""Clean revenue cohort analysis generated by the TableLore notebook rescue demo."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


DEFAULT_INPUT = Path("{display_path(DATA_PATH)}")
DEFAULT_OUTPUT = Path("{display_path(summary_path)}")


def load_revenue(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    required = {{"month", "customer_id", "segment", "revenue"}}
    missing = required.difference(frame.columns)
    if missing:
        raise ValueError(f"Missing required columns: {{', '.join(sorted(missing))}}")
    return frame


def summarize_revenue(frame: pd.DataFrame) -> pd.DataFrame:
    return (
        frame.groupby(["month", "segment"], as_index=False)["revenue"]
        .sum()
        .sort_values(["month", "segment"])
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run clean revenue cohort analysis.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    summary = summarize_revenue(load_revenue(args.input))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(args.output, index=False)
    print(f"Wrote {{args.output}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def rescue_report(cell_count: int, code_cell_count: int, has_hidden_state: bool, output_dir: Path) -> str:
    hidden_state_line = (
        "Detected hidden state from an in-place filtered dataframe and a mutable focus segment."
        if has_hidden_state
        else "No obvious hidden state markers were detected."
    )
    return f"""# Notebook Rescue Report

Source notebook: `{display_path(NOTEBOOK_PATH)}`

## Inspection

- Total cells: {cell_count}
- Code cells: {code_cell_count}
- hidden state review: {hidden_state_line}

## Rescue Actions

- Converted implicit notebook state into a reproducible script.
- Made input and output paths explicit CLI parameters.
- Preserved the analysis intent: monthly revenue by segment.
- Left scratch-only exploration out of the durable script.

## Generated Artifacts

- Reproducible script: `{display_path(output_dir / "clean_revenue_analysis.py")}`
- Artifact manifest: `{display_path(output_dir / "artifact_manifest.md")}`
- Suggested output table: `{display_path(output_dir / "cohort_revenue_summary.csv")}`

Run the script with:

```bash
python3 {display_path(output_dir / "clean_revenue_analysis.py")}
```
"""


def artifact_manifest(output_dir: Path) -> str:
    return f"""# Artifact Manifest

| artifact | purpose |
| --- | --- |
| `{display_path(NOTEBOOK_PATH)}` | messy source notebook |
| `{display_path(DATA_PATH)}` | source revenue fixture |
| `{display_path(output_dir / "clean_revenue_analysis.py")}` | reproducible script |
| `{display_path(output_dir / "rescue_report.md")}` | rescue explanation and caveats |
| `{display_path(output_dir / "cohort_revenue_summary.csv")}` | expected script output |

The generated script can be reviewed, copied into an analysis folder, and rerun with explicit input and output paths.
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create TableLore notebook rescue demo artifacts.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir.resolve()
    cell_count, code_cell_count, has_hidden_state = read_notebook_summary()

    cleaned_script_path = output_dir / "clean_revenue_analysis.py"
    manifest_path = output_dir / "artifact_manifest.md"
    report_path = output_dir / "rescue_report.md"

    write_text(cleaned_script_path, clean_script(output_dir))
    write_text(manifest_path, artifact_manifest(output_dir))
    write_text(report_path, rescue_report(cell_count, code_cell_count, has_hidden_state, output_dir))

    print("TableLore notebook rescue demo artifacts written:")
    for path in [cleaned_script_path, manifest_path, report_path]:
        print(f"- {display_path(path)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
